name=uPerlin
version=1.0.0
author=AlexGyver <alex@alexgyver.ru>
maintainer=AlexGyver <alex@alexgyver.ru>
sentence=Light integer Perlin noise implementation
paragraph=Light integer Perlin noise implementation
category=Processing
url=https://github.com/GyverLibs/uPerlin
architectures=*